name: Rango
favicon: null
layout_spectrum: 0.565146273933351
typography_spectrum: 0.9852448310703039
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5349012997467071
  lightness: 0.44486131868325174
  saturation: 0.9797500153072178
  rhythmicContrast: 0.845955713884905
purpose: []
